version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: usuario123
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: taller
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_net

  app:
    image: carlosdeus/my-node-app:latest  # Imagen publicada en Docker Hub
    ports:
      - 13000:3000  # Acceso web desde el puerto 13000
    environment:
      DB_HOST: db           # Nombre del servicio de base de datos
      DB_USER: usuario123
      DB_PASSWORD: 123456
      DB_NAME: taller
    depends_on:
      - db
    networks:
      - app_net
    volumes:
      - node_logs:/app/logs  # Volumen de ejemplo para logs o archivos internos

volumes:
  postgres_data:
  node_logs:

networks:
  app_net:
    driver: bridge
